### ISSUE TITLE
After deleting an entry, when trying to submit the same entry again, it is not showing in the Data Matrix

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/DRC-Portal-Issues#80]
Tried submitting a code asset, namely ETL script URL (https://github.com/MaayanLab/LINCS-metadata). 
It worked well, but then I deleted it because I wanted to edit the description and there is no edit option.
After resubmitting it, it seems to be updated in the database, but the entry is not displayed in the Data Matrix.

**Comment by u8sand** [comment]
Hi @AviMaayan it seems to be available now, is it possible that this update just took some time to propagate?
![image](https://github.com/user-attachments/assets/215b0d36-b771-472f-b346-3820deaf1ea2)

**Comment by u8sand** [comment]
Updating the title of a url is not currently possible, this is because there is no edit capability and a "delete" will preserve the record so a re-creation would result in a conflict.
Either we could use a different primary key (uuid) or we can allow editing of, in particular, these types of url-based assets.
